//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int ID_User { get; set; }
        public string User_Name { get; set; }
        public string Full_Name { get; set; }
        public string Email_User { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public string Password_User { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
