//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color_De
    {
        public int IdColor { get; set; }
        public int ID_Details { get; set; }
        public string ColorPr_Name { get; set; }
        public string Img_Pro { get; set; }
    
        public virtual Detail Detail { get; set; }
    }
}
