//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID_OderDetail { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> ID_Product { get; set; }
    
        public virtual OrderPro OrderPro { get; set; }
        public virtual Product Product { get; set; }
    }
}
